import { DockManager } from "./DockManager.js";
import { DockNode } from "./DockNode.js";
import { DraggableContainer } from "./DraggableContainer.js";
import { EventHandler } from "./EventHandler.js";
import { PanelContainer } from "./PanelContainer.js";
import { Point } from "./Point.js";
import { ResizableContainer } from "./ResizableContainer.js";
import { IContextMenuProvider } from "./interfaces/IContextMenuProvider.js";
export declare class Dialog implements IContextMenuProvider {
    elementDialog: HTMLDivElement & {
        floatingDialog: Dialog;
    };
    draggable: DraggableContainer;
    panel: PanelContainer;
    dockManager: DockManager;
    eventListener: DockManager;
    position: Point;
    resizable: ResizableContainer;
    disableResize: boolean;
    mouseDownHandler: any;
    onKeyPressBound: any;
    noDocking: boolean;
    isHidden: boolean;
    keyPressHandler: EventHandler;
    focusHandler: EventHandler;
    grayoutParent: PanelContainer;
    constructor(panel: PanelContainer, dockManager: DockManager, grayoutParent?: PanelContainer, disableResize?: boolean);
    saveState(x: number, y: number): void;
    static fromElement(id: string, dockManager: DockManager): Dialog;
    _initialize(): void;
    setPosition(x: number, y: number): void;
    getPosition(): Point;
    onFocus(): void;
    onMouseDown(e: PointerEvent): void;
    destroy(): void;
    resize(width: number, height: number): void;
    setTitle(title: string): void;
    setTitleIcon(iconName: string): void;
    bringToFront(): void;
    hide(): void;
    close(): void;
    remove(): void;
    show(): void;
    static createContextMenuContentCallback: (dialog: Dialog, documentMangerNodes: DockNode[]) => Node[];
    createContextMenuItems(): Node[];
}
