import { DockManager } from "../DockManager.js";
import { PanelContainer } from "../PanelContainer.js";
import { PanelType } from "../enums/PanelType.js";
import { DockNode } from "../DockNode.js";
export declare class DockSpawnTsWebcomponent extends HTMLElement {
    dockManager: DockManager;
    private slotId;
    private windowResizedBound;
    private slotElementMap;
    private observer;
    private initialized;
    private elementContainerMap;
    static style: CSSStyleSheet;
    constructor();
    private initDockspawn;
    getElementInSlot(slot: HTMLSlotElement): HTMLElement;
    private handleAddedChildNode;
    private handleRemovedChildNode;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private windowResized;
    resize(): void;
    getDockNodeForElement(elementOrContainer: HTMLElement | PanelContainer): DockNode;
    dockFill(element: HTMLElement, panelType?: PanelType, dockNode?: DockNode, title?: string, hideCloseButton?: boolean): DockNode;
    dockLeft(element: HTMLElement, panelType?: PanelType, dockNode?: DockNode, ratio?: number, title?: string, hideCloseButton?: boolean): DockNode;
    dockRight(element: HTMLElement, panelType?: PanelType, dockNode?: DockNode, ratio?: number, title?: string, hideCloseButton?: boolean): DockNode;
    dockUp(element: HTMLElement, panelType?: PanelType, dockNode?: DockNode, ratio?: number, title?: string, hideCloseButton?: boolean): DockNode;
    dockDown(element: HTMLElement, panelType?: PanelType, dockNode?: DockNode, ratio?: number, title?: string, hideCloseButton?: boolean): DockNode;
    floatDialog(element: HTMLElement, x: number, y: number, width: number, height: number, panelType?: PanelType, title?: string, hideCloseButton?: boolean): import("../Dialog.js").Dialog;
}
